version: '3.8'

services:
  db:
    image: postgres:15
    container_name: wallet-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - wallet-network

  wallet-service:
    build:
      context: ./
    container_name: wallet-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_LIQUIBASE_ENABLED=true
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.yaml
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge
